# Site settings
title: Jan Cantor
email: hello@jancantor.com
description: > # this means to ignore newlines until "baseurl:"
  Digital Product Designer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jancantor.com" # the base hostname & protocol for your site
my_username: jancantor

# Build settings
markdown: kramdown

# Grunt setup
exclude: [node_modules, Gruntfile.js, package.json]
